version: '3'

services:
  # MongoDB container
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test

  # Node.js application container
  node_app:
    build:
      context: exoplanets/  # Replace with your Node.js image details
    container_name: node_app
    restart: always
    ports:
      - "7000:3000"

  # Mongo Express container
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8000:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test